### ISSUE TITLE
Adding a "merge list" feature to YAML

### ISSUE THREAD

**Issue by eiva** [yaml/yaml-spec#28]
Few suggestions for new features (if yaml is still alive).

1. Merge lists
This is a really desired feature (even on stackoverflow)
```
source: *source
 - 1
 - 2
dest:
 -<< &source
 - 3
 -<< &source
```
Result:
```
source: [1,2]
dest: [1,2,3,1,2]
```

2. Inherit
Allow inheriting data from the source subfields.
```
source: *source
 field1:
  a: 1
  b: 2
 field2:
  c: 1
dest: &source
  field1:
   <<: &&
    d: 3
 field2:
   e: 4
```
Result for `dest`
```
dest:
  field1:
    a: 1
    b: 2
    d: 3
 field2:
   e: 4
```
