### ISSUE TITLE
Providing meta information (like schema file)

### ISSUE THREAD

**Issue by timonf** [yaml/yaml-spec#33]
Hi there!

I just want to drop an idea here (maybe for YAML 1.3?). Actually there are two "directives" available: 
- `%YAML` to identify the version of YAML
- `%TAG` to use as a shortcut for URI prefixes

It would be handy to have another one to add:
- `%META` to add any kind of meta information, which will not be parsed
- or more specific: `%SCHEMA` to specify a schema file.

Example:

```yaml
%YAML 1.3
%SCHEMA https://getcomposer.org/schema.json,json-schema
---
name: foo/bar-package
type: project
description: Composer example project
```

Schema directive:

    %SCHEMA <schema uri>[,<schema type>[,<schema version>]]

Another examples:

```
%SCHEMA resource.rx.yaml,rx
%SCHEMA composer_schema.json,json-schema,draft-04
%SCHEMA schema01.yaml,Kwalify
```

I think it's important  to support multiple systems using the second parameter. If you don't like the idea, I hope for something like a meta directive to add information such a schema document.

What do you think about this idea?
