### ISSUE TITLE
Would like to specify that a list of lists should be flattened

### ISSUE THREAD

**Issue by acampove** [yaml/yaml-spec#339]
Hi,

I have a file like:

```yaml
mammals: &mammals
  - lion
  - tiger
  - elephant

reptiles: &reptiles
  - snake
  - lizard
  - crocodile

animals:
  - *mammals
  - *reptiles
```

In the example above, `animals` is not a single list, but two and we would have to flatten this in the code. It would be good if we could somehow specify that these lists have to be flattened, e.g. with `- **mammals`.

**Comment by UnePierre** [comment]
Another syntax could follow that for appending maps, like:

```
mammals: &mammals
  - lion
  - tiger
  - elephant

reptiles: &reptiles
  - snake
  - lizard
  - crocodile

animals:
  <<:
    - *mammals
    - *reptiles
```

**Comment by ingydotnet** [comment]
I'd like to present [YAMLScript](https://yamlscript.org) as a solution for this.
YAMLScript embeds cleanly into YAML and is 100% valid YAML itself.
It can solve your `concat` need and about anything else for extending YAML.
It currently has YAML loaders in 10 languages: https://yamlscript.org/doc/bindings/

> For brevity I'll use the flow form where appropriate. It's the same data and semantics.
> ```
> mammals: &mammals [lion, tiger, elephant]
> reptiles: &reptiles [snake, lizard, crocodile]
> animals: [*mammals, *reptiles]
> ```

There are many ways to accomplish this in YAMLScript (YS).
Here's one:
```yaml
# File: 339.yaml
!yamlscript/v0:
mammals: &mammals [lion, tiger, elephant]
reptiles: &reptiles [snake, lizard, crocodile]
animals::
  apply concat::
  - *mammals
  - *reptiles
```

Then we load load it from the command line with:
```
$ ys -Y 339.yaml
mammals:
- lion
- tiger
- elephant
reptiles:
- snake
- lizard
- crocodile
animals:
- lion
- tiger
- elephant
- snake
- lizard
- crocodile
```
The `!yamlscript/v0:` line is needed for YS to eval any code in your file. It starts out in data mode, where plain scalars are strings or numbers. The `::` toggles the k/v pair between data mode and code mode. Thus the `apply concat` key is a code expression and it's value would have been code too but we toggled back with another `::`.

Let's make it a little better.

```yaml
!yamlscript/v0:
mammals: &mammals [lion, tiger, elephant]
reptiles: &reptiles [snake, lizard, crocodile]
animals: !:concat*
- *mammals
- *reptiles
```
does the same thing. You can put a function call in a tag. The function is applied to the node. The trailing `*` splats the sequence so that the `ys::std/concat` function is called like `concat(*mammals *reptiles)` and not `concat([*mammals *reptiles])`. You can use 100s of standard functions that way.

Let's look at how this file compiles:
```
$ ys -Uc 339.yaml
{"mammals" (_& 'mammals ["lion" "tiger" "elephant"]),
 "reptiles" (_& 'reptiles ["snake" "lizard" "crocodile"]),
 "animals" (apply concat [(_** 'mammals) (_** 'reptiles)])}
```

It's often the case that you have YAML where you want to concat or merge anchored structures like `&mammals` and `&reptiles` but you only care about the `animals` result. Unfortunately `mammals` and `reptiles` needs to be part of the document to use them, and thus they end up in the result too. YS let's you do this:
```yaml
--- !yamlscript/v0:
- &mammals [lion, tiger, elephant]
- &reptiles [snake, lizard, crocodile]
--- !yamlscript/v0:
animals: !:concat*
- *mammals
- *reptiles
```
YS only loads the final doc by default, but can access anchors in other docs. So now you only get animals:
```
$ ys -Y 339.yaml
animals:
- lion
- tiger
- elephant
- snake
- lizard
- crocodile
```

You could also use `load` to have the data in other files:
```yaml
# 339.yaml
--- !yamlscript/v0:
- &mammals ! load('mammals.yaml')
- &reptiles ! load('reptiles.yaml')
--- !yamlscript/v0:
animals: !:concat*
- *mammals
- *reptiles

# mammals.yaml
[lion, tiger, elephant]

# reptiles.yaml
[snake, lizard, crocodile]
```

We don't need to use anchors and aliases to name things, we can use variables:
```yaml
--- !yamlscript/v0
mammals =: load('mammals.yaml')
reptiles =: load('reptiles.yaml')
--- !yamlscript/v0:
animals: !:concat*
- ! mammals
- ! reptiles
```
Note the first tag changed from `!yamlscript/v0:` to `!yamlscript/v0`. That starts the document in code mode.

Data mode allows you to specify variable assignments inline, so we can go back to a single document:
```yaml
--- !yamlscript/v0:
mammals =: load('mammals.yaml')
reptiles =: load('reptiles.yaml')
animals: !:concat*
- ! mammals
- ! reptiles
```

There are other ways to call `concat` here:
```yaml
--- !yamlscript/v0:
mammals =: load('mammals.yaml')
x =: &R load('reptiles.yaml')
animals:: concat(mammals *R)
animals:: mammals.concat(*R)
animals:: mammals + *R
```

Just to show how flexible YS is...

Data mode also has a auto insert functionality for data mode sequences:

```yaml
--- !yamlscript/v0
mammals =: load('mammals.yaml')
x =: &R load('reptiles.yaml')
--- !yamlscript/v0:
animals:
- aardvark
- :: mammals
- mastadon
- :: *R
- zebra
```
which produces:
```yaml
animals:
- aardvark
- lion
- tiger
- elephant
- mastadon
- snake
- lizard
- crocodile
- zebra
```

The cool thing about this is you can put conditional code on these inserts. `when rand(100) > 50` evaluates to true half the time:
```yaml
--- !yamlscript/v0
mammals =: load('mammals.yaml')
x =: &R load('reptiles.yaml')
--- !yamlscript/v0:
animals:
- aardvark
- :when rand(100) > 50: mammals
- mastadon
- :when rand(100) > 50: *R
- zebra
```
This is probably not useful but proves the point. The conditional insert here is shorthand for:
```yaml
- aardvark
- ::
    when rand(100) > 50:
      mammals
```
The code starting with `when` could be any code at all. It it evaluates to a sequence, the sequence is inserted. If evals to `nil` nothing happens.

Let's compile it:
```
(def mammals (load "mammals.yaml"))
(+++ (def x (_& 'R (load "reptiles.yaml"))))
{"animals"
 (concat
  ["aardvark"]
  (when (> (rand 100) 50) mammals)
  ["mastadon"]
  (when (> (rand 100) 50) (_** 'R))
  ["zebra"])}
```

> All the `::` stuff also works in mappings too for inline merging, conditional or not. (iow, the YS way to do `<<` stuff in mappings)

So back to your original. You can also do:
```yaml
--- !yamlscript/v0:
mammals: &mammals
  - lion
  - tiger
  - elephant

reptiles: &reptiles
  - snake
  - lizard
  - crocodile

animals:
  - :: *mammals
  - :: *reptiles
```
