### ISSUE TITLE
Current version of the YAML specification could leave implementions open to Denial of Service Attacks

### ISSUE THREAD

**Issue by raesene** [yaml/yaml-spec#45]
The current version of the YAML specification does not mention the idea of limiting entity expansion.  Unlimited entity expansion can lead to denial of service risks in code which processes untrusted YAML documents.  

This class of attacks is commonly called a [Billion Laughs Attack](https://en.wikipedia.org/wiki/Billion_laughs_attack).  There is an example YAML document in the referenced Wikipedia page which demonstrates this issue.

This issue has recently shown up in the Kubernetes project as a possible issue in their API Server component (details [here](https://github.com/kubernetes/kubernetes/issues/83253)).  The code underlying that was the [go-yaml](https://github.com/go-yaml/yaml) library.  

In conversation with the library author regarding this issue, it was mentioned that the implementation complied with the specification and that it would be best if the specification was modified to include the option or requirement to limit entity expansion to address this, rather than necessarily just addressing it in individual implementations.

**Comment by liggitt** [comment]
As an example, the JSON spec explicitly permits implementations to limit nesting depth, string length, and document size: https://tools.ietf.org/html/rfc7159#section-9

**Comment by Thom1729** [comment]
I'm a bit confused as to exactly what is happening.

The example document from Wikipedia:

```yaml
a: &a ["lol","lol","lol","lol","lol","lol","lol","lol","lol"]
b: &b [*a,*a,*a,*a,*a,*a,*a,*a,*a]
c: &c [*b,*b,*b,*b,*b,*b,*b,*b,*b]
d: &d [*c,*c,*c,*c,*c,*c,*c,*c,*c]
e: &e [*d,*d,*d,*d,*d,*d,*d,*d,*d]
f: &f [*e,*e,*e,*e,*e,*e,*e,*e,*e]
g: &g [*f,*f,*f,*f,*f,*f,*f,*f,*f]
h: &h [*g,*g,*g,*g,*g,*g,*g,*g,*g]
i: &i [*h,*h,*h,*h,*h,*h,*h,*h,*h]
```

The document is only “linearly” big; it contains only “linearly” many nodes and I don't see why it should require more than “linear” memory. If you try to do a naive tree traversal it will blow up, but YAML documents can contain reference cycles, which would make a tree traversal run forever anyway. You could run into trouble if you have a tree traversal algorithm plus a cycle detector; the example document above proves that this is not a sane way to iterate over an arbitrary graph.

It looks like the application is trying to “flatten” a YAML graph to remove aliases. This is clearly impossible in the general case because of cycles, so I must presume that they are checking for cycles and assuming that acyclic documents can be safely flattened.

I'm not sure that limiting nesting depth is the way to go here. Even with a fixed nesting depth, a polynomial “billion laughs” attack is possible; if the depth is as little as two, then the attack can still be cubic, which still sounds problematic. A system relying on nesting depth to dodge this attack would have to set a very low depth. On the other hand, just setting a limit on the number of flattened nodes (or number of flattened alias nodes) would seem to solve the problem quite directly without affecting legitimate uses of alias nodes.
